# Generated by Django 3.1.1 on 2021-01-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tensionblock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold', models.CharField(max_length=20)),
                ('fingers_used', models.CharField(max_length=7)),
                ('grip_used', models.CharField(max_length=20)),
                ('weight', models.IntegerField(verbose_name='weight')),
                ('duration', models.IntegerField(verbose_name='Duration')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
            ],
        ),
    ]
